const colors = {
  offWhite: '#cacbcb',
  white: '#fff',
  black: 'black',
  checkBoxBorder: "gray",
  checkBoxTick: "gray",
  checkBoxBackground: "white",
  textInputColor: '#799ab5',
  labelText: '#868585',
  lightGrey: '#F2F1F1',
  grey: '#9B9B9B',
  darkGrey: '#48494B',
  success: "#0D793D",
  errorRed: '#C45156',
  silver: 'silver',
  mustardBrown: '#B85905',
  yellow: '#F1AE11',
  seaGreen: '#0c9d9b',
  themeBlue: '#365985',
  lightGreen: '#40AFB5',
  purple: "#483B82",
  specializationTextColor: '#5d5c5c',
  whoAreYouBox_1: "#FFF1CB",
  whoAreYouBox_2: "#C2E9E8",
  blue: "#365985",
  green: "#39B029",
  errorText: "red",
  errorBorder: "red",
  oceanBlue: "#E5EFF4",
  successText: "green",
  // Login
  inputBackground: '#fff',
  inputTextColor: "black",
  inputBorder: "#a7a7a7",
  inputPlaceholderColor: "#6e6a6a",
  checkBoxBorder: "#6b6969",
  splashEye: "#6e6a6a",
  signUpLink: "#365985",
  signInButton: "#365985",
  forgotPassword: "#0e5688",
  signInButtonText: "#ffffff",
  signInBorder: "black",
  passwordEye: "gray",
  rememberMe: "#6e6a6a",
  connectWith: "black",
  newHere: "black",
  // Registration
  signUpRegistration: "#365985",
  signUpButton: "#F8AC0E",
  alreadyAccountColor: "#365985",
  //Side Drawer
  dividerLines: "silver",
  signOutBorder: "black",
  organisationItem: "silver",
  chevronIconColor: "silver",
  createNetwork: "#6b6868",
  networkItems: "#6b6868",
  showMore: "black",
  closeIcon: "white",
  //Create Network
  headerBottomBorder: "black",
  headerBackIcon: "#365985",
  headerTextColor: "black",
  headerButtonColor: "#365985",
  uploadPhotoCN: "silver",
  uploadBorderColor: "#365985",
  checkboxBackCN: "silver",
  checkboxBorderCN: "silver",
  describeTextCN: "silver",
  describeTextBorderCN: "#365985",
  addDetailsTextCN: "#365985",
  inputBorderCN: "black",
  inputPlaceholderCN: "black",
  darkContent: 'dark-content',
  transparent: 'transparent',
  //Network List 
  networkBackground: '#EEEAEB',
  pink: 'pink',
  // My Networks
  createButton: "#365985",
  // Header Gradient Color
  darkBlue: "#083352",
  lightBlue: "#0F5387",
  // Join Network Request
  borderTopColorJN: "#6e6d6d",
  joinNetworkButtonColor: '#0e5688',
  //splash
  themeYellow: "#f4ad0a",

};

export default colors;
