//PROFILE
export const SET_USER_ID = "SET_USER_ID";
export const SET_FIRST_NAME = "SET_FIRST_NAME";
export const SET_LAST_NAME = "SET_LAST_NAME";
export const SET_COUNTRY_NAME = "SET_COUNTRY_NAME";
export const SET_OCCUPATION = "SET_OCCUPATION";
export const SET_DATE_OF_BIRTH = "SET_DATE_OF_BIRTH";
export const SET_GENDER = "SET_GENDER";
export const SET_PHONE_NUMBER = "SET_PHONE_NUMBER";
export const SET_EMAIL = "SET_EMAIL";
export const SET_ADDRESS = "SET_ADDRESS";
export const SET_PROFILE_PICTURE = "SET_PROFILE_PICTURE";
export const SET_EDUCATION_LIST = "SET_EDUCATION_LIST";
export const SET_EXPERIENCE_LIST = "SET_EXPERIENCE_LIST";
export const SET_ABOUT = "SET_ABOUT";
export const SET_ABOUT_DESCRIPTION = "SET_ABOUT_DESCRIPTION";
export const SET_CITY = "SET_CITY";
export const SET_STATE1 = "SET_STATE1";
export const RESET_PROFILE = "RESET_PROFILE";
//NETWORKS
export const SET_USER_CONNECTED_NETWORKS_LIST = "SET_USER_CONNECTED_NETWORKS_LIST";
export const SET_PUBLIC_NETWORKS_LIST = "SET_PUBLIC_NETWORKS_LIST";
export const RESET_NETWORKS = "RESET_NETWORKS";
//NOTIFICATIONS
export const SET_NOTIFICATIONS_LIST = "SET_NOTIFICATIONS_LIST";
//CONNECTION
export const SET_TOTAL_CONNECTIONS = "SET_TOTAL_CONNECTIONS";
export const SET_CONNECTION_INVITATION_LIST = "SET_CONNECTION_INVITATION_LIST";
export const SET_CONNECTIONS_LIST = "SET_CONNECTIONS_LIST";
//POSTS
export const SET_USER_POSTS_LIST = "SET_USER_POSTS_LIST";
export const SET_NETWORK_POSTS_LIST = "SET_NETWORK_POSTS_LIST";
export const SET_FEED_POSTS_LIST = "SET_FEED_POSTS_LIST";
export const RESET_POSTS = "RESET_POSTS";
// general
export const SET_ERROR_MSG = "SET_ERROR_MSG";
export const SET_SUCCESS_MSG = "SET_SUCCESS_MSG";
export const RESET_ERROR_MSG = "RESET_ERROR_MSG";
export const RESET_SUCCESS_MSG = "RESET_SUCCESS_MSG";

