//USER
export const SET_USER = "SET_USER";
// NETWORK LIST
export const SET_NETWORKS = "SET_NETWORKS"
//PROFILE
export const SET_FIRST_NAME = "SET_FIRST_NAME";
export const SET_LAST_NAME = "SET_LAST_NAME";
export const SET_COUNTRY_NAME = "SET_COUNTRY_NAME";
export const SET_OCCUPATION = "SET_OCCUPATION";
export const SET_DATE_OF_BIRTH = "SET_DATE_OF_BIRTH";
export const SET_GENDER = "SET_GENDER";
export const SET_PHONE_NUMBER = "SET_PHONE_NUMBER";
export const SET_EMAIL = "SET_EMAIL";
export const SET_ADDRESS = "SET_ADDRESS";
export const SET_EDUCATION_LIST = "SET_EDUCATION_LIST";
export const SET_EXPERIENCE_LIST = "SET_EXPERIENCE_LIST";
export const RESET_PROFILE = "RESET_PROFILE";
//NOTIFICATIONS
export const SET_NOTIFICATIONS_LIST = "SET_NOTIFICATIONS_LIST";
export const SET_NOTIFICATIONS_BADGE = "SET_NOTIFICATIONS_BADGE";
//CONNECTION
export const SET_TOTAL_CONNECTIONS = "SET_TOTAL_CONNECTIONS";
export const SET_CONNECTION_INVITATION_LIST = "SET_CONNECTION_INVITATION_LIST";
export const SET_CONNECTIONS_LIST = "SET_CONNECTIONS_LIST";
// general
export const SET_ERROR_MSG = "SET_ERROR_MSG";
export const SET_SUCCESS_MSG = "SET_SUCCESS_MSG";
export const RESET_ERROR_MSG = "RESET_ERROR_MSG";
export const RESET_SUCCESS_MSG = "RESET_SUCCESS_MSG";
//POSTS
export const SET_POST = "SET_POST";

